# ============================================================
# dbt Project Configuration
# ============================================================

name: 'ovecell_assignment'
version: '1.0.0'
profile: 'ovecell_assignment'

# Paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# ============================================================
# Models Configuration
# ============================================================
models:
  ovecell_assignment:
    # Default materialization (can be overridden below)
    +materialized: view

    # --- Source data cleanup and structuring ---
    staging:
      +materialized: table     # staging tables are persisted (for auditing)
      +tags: ["staging"]

    # --- Intermediate transformations ---
    intermediate:
      +materialized: view      # keep joins and enrichments light on memory
      +tags: ["intermediate"]

    # --- Final analytical outputs ---
    marts:
      +materialized: table     # final models for BI/reporting
      +tags: ["marts"]


